version: '2'
services:
  samplemvn-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/SampleMvn/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=SampleMvn
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
